### ISSUE TITLE
php curl module ignores proxychains

### ISSUE THREAD

**Issue by kai-rn** [rofl0r/proxychains-ng#10]
try this simple script:

```
<?php
echo "file_get_contents:\n";
echo file_get_contents("http://ifconfig.me/ip");
echo "curl:\n";
$ch=curl_init();
curl_setopt($ch,CURLOPT_URL,"http://ifconfig.me/ip");
curl_setopt($ch,CURLOPT_HEADER,0);
curl_exec($ch);
curl_close($ch);
```

assume that my real ip is 123.45.67.89 and socks proxy ip is 10.10.10.10
without proxychains:

```
# php php_curl.php 
file_get_contents:
123.45.67.89
curl:
123.45.67.89
```

with proxychains:

```
# proxychains php php_curl.php 
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
file_get_contents:
10.10.10.10
curl:
123.45.67.89
```

i.e. curl was not proxified even with proxychains library preloaded.

**Comment by speeddragon** [comment]
I'm having the same issue on Debian, but in OSX that issue doesn't happen. Any thoughts ?

**Comment by rofl0r** [comment]
it's a bug in GLIBCs dynlinker. someone would need to stand up and report the issue on their bugtracker. this [comment ](https://github.com/rofl0r/proxychains-ng/issues/10#issuecomment-12632041) explains what happens.

**Comment by rofl0r** [comment]
i've created a minimal testcase to reproduce the issue: https://0x0.st/fDK.gz
it's 3 small C files and a build.sh. when you run `build.sh`, you should see the output
```
hooked
hooked
```
however on GLIBC it probably prints `hooked` only once.
can anyone test this ? i don't have a system with GLIBC.
when we have it confirmed, someone can take the testcase and open a bug report on the GLIBC bugtracker.

**Comment by kai-rn** [comment]
On 2017-01-15 07:01, rofl0r wrote:
> i've created a minimal testcase to reproduce the issue: 
> https://0x0.st/fDK.gz
> it's 3 small C files and a build.sh. when you run `build.sh`, you
> should see the output
> ```
> hooked
> hooked
> ```
> however on GLIBC it probably prints `hooked` only once.
> can anyone test this ? i don't have a system with GLIBC.
> when we have it confirmed, someone can take the testcase and open a
> bug report on the GLIBC bugtracker.

problem:

     dlopen_bug> gcc preload.c -Wall -shared -fPIC -ldl -o preload.so
     preload.c: In function ‘init’:
     preload.c:9:19: error: ‘RTLD_NEXT’ undeclared (first use in this 
function)
       origputs = dlsym(RTLD_NEXT, "puts");
                    ^

fix:

     gcc preload.c -D_GNU_SOURCE -Wall -shared -fPIC -ldl -o preload.so

or add a line:

     --- preload.c   2017-01-15 14:13:06.951753115 +0700
     +++ preload_fix.c       2017-01-15 14:13:03.459753218 +0700
     @@ -1,3 +1,4 @@
     +#define _GNU_SOURCE
      #include <pthread.h>
      #include <dlfcn.h>
      pthread_once_t init_once = PTHREAD_ONCE_INIT;


problem:

     dlopen_bug> sh build.sh
     app.c: In function ‘main’:
     app.c:11:1: warning: control reaches end of non-void function 
[-Wreturn-type]
      }
      ^
     ./app: symbol lookup error: ./preload.so: undefined symbol: 
pthread_once

fix:

     gcc preload.c -D_GNU_SOURCE -lpthread -Wall -shared -fPIC -ldl -o 
preload.so


But in the end it surprisingly works on Centos 6.8 gcc 4.4.7 glibc 2.12 
(system of the test case with php and curl) and openSUSE 13.2 gcc 4.8.3 
glibc 2.19:

     dlopen_bug> sh build.sh
     app.c: In function ‘main’:
     app.c:11:1: warning: control reaches end of non-void function 
[-Wreturn-type]
      }
      ^
     hooked
     hooked

**Comment by rofl0r** [comment]
thanks. what was the output of the testcase once you got it to run, @kai-rn ?

**Comment by kai-rn** [comment]
Github broke my email formatting, press on "..." icon to see the rest of 
the email.
The output is as follows:

> But in the end it surprisingly works on Centos 6.8 gcc 4.4.7 glibc 2.12 
> (system of the test case with php and curl) and openSUSE 13.2 gcc 4.8.3 
> glibc 2.19:
> 
> dlopen_bug> sh build.sh
>  app.c: In function ‘main’:
>  app.c:11:1: warning: control reaches end of non-void function 
> [-Wreturn-type]
>  }
>  ^
> hooked
> hooked
>

**Comment by rofl0r** [comment]
damn. even when you replace `RTLD_NOW` with `RTLD_LAZY` in app.c ?

**Comment by kai-rn** [comment]
On 2017-01-15 19:28, rofl0r wrote:
> damn. even when you replace `RTLD_NOW` with `RTLD_LAZY` in app.c ?

still works.

> hooked
> hooked
