### ISSUE TITLE
fails to build on openbsd 5.7 i386/amd64 - gmake: *** [src/libproxychains.o] Error 1

### ISSUE THREAD

**Issue by cam13** [rofl0r/proxychains-ng#83]
$ git clone https://github.com/rofl0r/proxychains-ng.git 
Cloning into 'proxychains-ng'...
remote: Counting objects: 983, done.
remote: Total 983 (delta 0), reused 0 (delta 0), pack-reused 983
Receiving objects: 100% (983/983), 536.37 KiB | 179.00 KiB/s, done.
Resolving deltas: 100% (637/637), done.
Checking connectivity... done.

$ cd proxychains-ng/                                                                                                                                                                                                                                                                                                                                            
$ ./configure
Done, now run gmake && gmake install

$ gmake
cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -DIS_BSD -DIS_OPENBSD   -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/nameinfo.o src/nameinfo.c
printf '#define VERSION "%s"\n' "$(sh tools/version.sh)" > src/version.h
cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -DIS_BSD -DIS_OPENBSD   -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/version.o src/version.c
cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -DIS_BSD -DIS_OPENBSD   -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/core.o src/core.c
cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -DIS_BSD -DIS_OPENBSD   -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/common.o src/common.c
cc -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -DIS_BSD -DIS_OPENBSD   -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/libproxychains.o src/libproxychains.c
src/libproxychains.c: In function 'is_v4inv6':
src/libproxychains.c:311: error: 'const struct in6_addr' has no member named 's6_addr32'
src/libproxychains.c:311: error: 'const struct in6_addr' has no member named 's6_addr32'
src/libproxychains.c:312: error: 'const struct in6_addr' has no member named 's6_addr16'
src/libproxychains.c:312: error: 'const struct in6_addr' has no member named 's6_addr16'
src/libproxychains.c:313: warning: control reaches end of non-void function
src/libproxychains.c: In function 'connect':
src/libproxychains.c:342: error: 'struct in6_addr' has no member named 's6_addr32'
Makefile:81: recipe for target 'src/libproxychains.o' failed
gmake: *** [src/libproxychains.o] Error 1

**Comment by rofl0r** [comment]
openbsd support is currently non-functional due to some dynlinker issue that's impossible to debug (for me, as i'm lacking an openbsd developer qemu image with all the debug info, sources, necessary devel tools etc). if you feel that you may get it to work, you can start with the 4.10 release which compiles on openbsd (just check out the release tag or download the release tarball). if you have success, we can merge your changes into master and fix the incompabilities in the new ipv6 code.

**Comment by cam13** [comment]
thanks for the quick reply.
I've taken a look at it and here's a quick workaround to make it compile on both 5.7 i386/amd64 and -current.

diff --git a/src/common.h b/src/common.h
index 5335bd1..2867775 100644
--- a/src/common.h
+++ b/src/common.h
@@ -18,5 +18,9 @@ extern const char *proxy_state_strmap[];
 char *get_config_path(char* default_path, char* pbuf, size_t bufsize);
 void pc_stringfromipv4(unsigned char *ip_buf_4_bytes, char *outbuf_16_bytes);
 
+#define s6_addr8  __u6_addr.__u6_addr8
+#define s6_addr16 __u6_addr.__u6_addr16
+#define s6_addr32 __u6_addr.__u6_addr32
+
 //RcB: DEP "common.c"
 #endif

**Comment by rofl0r** [comment]
if you can put that code into the right ifdefs for openbsd i'd happily merge the fix in form of a pull request.
something like
```c
#if !defined(s6_addr16 ) && defined(OPENBSD_MAGIC_MACRO)
#define s6_addr16 __u6_addr.__u6_addr16
#define s6_addr32 __u6_addr.__u6_addr32
#endif
```
the change would need to go into src/libproxychains.c after the inclusion of common.h since common.h doesnt include netinet/in.h which is necessary for the definition check

**Comment by rofl0r** [comment]
@cam13 could you test if this patch (applied to master without your patch) fixes the issue for you ? http://sprunge.us/RhUe
(need to re-run configure)

**Comment by cam13** [comment]
sorry for the late reply. applied your patch and build is perfect:

$ ./configure
checking whether netinet/in.h defines s6_addr16 ... no
checking whether netinet/in.h defines __u6_addr.__u6_addr16 ... yes
Done, now run gmake && gmake install
(7945) /tmp/proxychains-ng (git::master)
$ gmake
cc -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32 -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -DIS_BSD -DIS_OPENBSD   -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/nameinfo.o src/nameinfo.c
printf '#define VERSION "%s"\n' "$(sh tools/version.sh)" > src/version.h
cc -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32 -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -DIS_BSD -DIS_OPENBSD   -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/version.o src/version.c
cc -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32 -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -DIS_BSD -DIS_OPENBSD   -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/core.o src/core.c
cc -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32 -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -DIS_BSD -DIS_OPENBSD   -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/common.o src/common.c
cc -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32 -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -DIS_BSD -DIS_OPENBSD   -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/libproxychains.o src/libproxychains.c
cc -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32 -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -DIS_BSD -DIS_OPENBSD   -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/allocator_thread.o src/allocator_thread.c
cc -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32 -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -DIS_BSD -DIS_OPENBSD   -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/ip_type.o src/ip_type.c
src/ip_type.c:4: warning: missing braces around initializer
src/ip_type.c:4: warning: (near initialization for 'ip_type_localhost.addr.v4.octet')
cc -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32 -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -DIS_BSD -DIS_OPENBSD   -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/hostsreader.o src/hostsreader.c
cc -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32 -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -DIS_BSD -DIS_OPENBSD   -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/hash.o src/hash.c
cc -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32 -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -DIS_BSD -DIS_OPENBSD   -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/debug.o src/debug.c
cc -shared -fPIC -Wl,--no-as-needed  -lpthread -Wl,-soname=libproxychains4.so  \
        -o libproxychains4.so src/nameinfo.o src/version.o src/core.o src/common.o src/libproxychains.o src/allocator_thread.o src/ip_type.o src/hostsreader.o src/hash.o src/debug.o
cc -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32 -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe -DIS_BSD -DIS_OPENBSD   -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.so\"  -fPIC -c -o src/main.o src/main.c
cc src/main.o src/common.o  -o proxychains4
